### ISSUE TITLE
Translation: Spanish (es-es)

### ISSUE THREAD

**Issue by stefanbohacek** [jointhefediverse-net/jointhefediverse.net#12]

**Comment by deimidis** [comment]
Hi, I made a branch (spanish) and made a pull request for the first file, just to test if everything is working

**Comment by stefanbohacek** [comment]
@deimidis Just a heads-up, the translation directory structure has changed and each locale now has its own folder and .json file with locale information. https://github.com/jointhefediverse-net/jointhefediverse.net/tree/main/translations
