### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by AhmadDakhlallah** [jointhefediverse-net/jointhefediverse.net#37]
Hello,

There is an issue with the table at this URL:
https://jointhefediverse.net/join

It has the "text-start" set to "text-align: left!important;"
Change that to "text-align: right;" when in an RTL language in order to display the text correctly. 

I also highly advise using the font Tajawal to display the Arabic language:
https://fonts.google.com/specimen/Tajawal?subset=arabic&noto.script=Arab

Thank you!

**Comment by stefanbohacek** [comment]
Thank you for catching these!

Fixed with https://github.com/jointhefediverse-net/jointhefediverse.net/pull/38 and  https://github.com/jointhefediverse-net/jointhefediverse.net/pull/39.

**Comment by stefanbohacek** [comment]
I'd also love to hear from @hoteit on these changes, if you have a moment.

**Comment by stefanbohacek** [comment]
No problem at all, thank you so much for reviewing this!
