### ISSUE TITLE
Update alternatives for Reddit/Hacker News

### ISSUE THREAD

**Issue by AndrewMathis13** [jointhefediverse-net/jointhefediverse.net#83]
The /kbin project is discontinued, and as such should be removed.

However, there are two other projects that should be added to the category:

/mbin (community fork of /kbin) 
- [https://joinmbin.org/](https://joinmbin.org/)

PieFed (another ActivityPub powered link aggregator platform)
- [https://join.piefed.social/](https://join.piefed.social/)

**Comment by stefanbohacek** [comment]
@AndrewMathis13 Thank you for opening the issue, I went ahead and updated the site with https://github.com/jointhefediverse-net/jointhefediverse.net/commit/6b7a356f391763ac4b26748cc89a149757984934.
