### ISSUE TITLE
site really needs a favicon!

### ISSUE THREAD

**Issue by wakest** [jointhefediverse-net/jointhefediverse.net#87]
realized that there is no favicon showing up, not sure if there was one at somepoint and its just broken or what

<img width="791" alt="image" src="https://github.com/user-attachments/assets/5db35bc8-b522-4cb4-b69a-fade69718a65">

seems easy enough fix, you can grab one from either of these projects:
https://joinfediverse.wiki/
https://symbol.fediverse.info/

**Comment by stefanbohacek** [comment]
Ah, good catch, thank you! Let me look into what would make the most sense.

**Comment by wakest** [comment]
https://emojos.santisbon.me/ also has a version of the asterism symbol that looks quite cute

**Comment by stefanbohacek** [comment]
Nice, thank you for sharing that!

**Comment by stefanbohacek** [comment]
I decided to go with the pentagram logo. While this one is not my personal favorite, it is more recognizable.

Definitely open to revisit this choice in the future.
