### ISSUE TITLE
Translation: Polish (pl)

### ISSUE THREAD

**Issue by stefanbohacek** [jointhefediverse-net/jointhefediverse.net#9]

**Comment by unsolaci** [comment]
Hey, I just stumbled upon here looking to try and translate the site to Polish, but I see that it's already in progress 🚀.

If you need any help, let me know. Not a linguist, just your regular native Polish speaker. 

Otherwise, thanks for picking this up @LukaszH77! 🎉

**Comment by stefanbohacek** [comment]
@unsolaci Thank you, really appreciate it!
