### ISSUE TITLE
Translation: Russian (ru)

### ISSUE THREAD

**Issue by bazylevnik0** [jointhefediverse-net/jointhefediverse.net#92]
^_^

**Comment by stefanbohacek** [comment]
Hi @bazylevnik0! Sorry about the confusion, this repo is for a separate project, https://jointhefediverse.net, which is not associated with https://joinfediverse.wiki, but I frequently link to this site.

You can still contribute to the wiki if you sign up for an account.

**Comment by stefanbohacek** [comment]
@bazylevnik0 Great, I'm sure they will appreciate your contribution!
